from PyQt6 import QtCore, QtWidgets

class Ui_BMIFenster(object):
    def setupUi(self, BMIFenster):
        BMIFenster.setObjectName("BMIFenster")
        BMIFenster.resize(682, 736)
        self.centralwidget = QtWidgets.QWidget(parent=BMIFenster)
        self.centralwidget.setObjectName("centralwidget")
        self.labelGewicht = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelGewicht.setGeometry(QtCore.QRect(40, 40, 49, 16))
        self.labelGewicht.setObjectName("labelGewicht")
        self.eingabeGewicht = QtWidgets.QDoubleSpinBox(parent=self.centralwidget)
        self.eingabeGewicht.setGeometry(QtCore.QRect(90, 40, 62, 22))
        self.eingabeGewicht.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.eingabeGewicht.setObjectName("eingabeGewicht")
        self.eingabeGewicht.setMinimum(1.0)
        self.eingabeGewicht.setMaximum(500.0)
        self.eingabeGewicht.setSingleStep(0.5)
        self.labelGroesse = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelGroesse.setGeometry(QtCore.QRect(170, 40, 49, 16))
        self.labelGroesse.setObjectName("labelGroesse")
        self.eingabeGroesse = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.eingabeGroesse.setGeometry(QtCore.QRect(210, 40, 42, 22))
        self.eingabeGroesse.setObjectName("eingabeGroesse")
        self.eingabeGroesse.setMinimum(1)
        self.eingabeGroesse.setMaximum(300)
        self.buttonCalcBmi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonCalcBmi.setGeometry(QtCore.QRect(280, 40, 91, 24))
        self.buttonCalcBmi.setObjectName("buttonCalcBmi")
        self.buttonCalcBmi.clicked.connect(self.btn_click)
        self.labelBild = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelBild.setGeometry(QtCore.QRect(10, 160, 661, 531))
        self.labelBild.setObjectName("labelBild")
        self.labelBMI = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelBMI.setGeometry(QtCore.QRect(40, 90, 49, 16))
        self.labelBMI.setObjectName("labelBMI")
        self.labelBMAusgabe = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelBMAusgabe.setGeometry(QtCore.QRect(100, 90, 101, 16))
        self.labelBMAusgabe.setText("")
        self.labelBMAusgabe.setObjectName("labelBMAusgabe")
        BMIFenster.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=BMIFenster)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 682, 22))
        self.menubar.setObjectName("menubar")
        BMIFenster.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=BMIFenster)
        self.statusbar.setObjectName("statusbar")
        BMIFenster.setStatusBar(self.statusbar)

        self.retranslateUi(BMIFenster)
        QtCore.QMetaObject.connectSlotsByName(BMIFenster)

    def retranslateUi(self, BMIFenster):
        _translate = QtCore.QCoreApplication.translate
        BMIFenster.setWindowTitle(_translate("BMIFenster", "BMI Rechner"))
        self.labelGewicht.setText(_translate("BMIFenster", "Gewicht"))
        self.labelGroesse.setText(_translate("BMIFenster", "Größe"))
        self.buttonCalcBmi.setText(_translate("BMIFenster", "BMI ermitteln"))
        self.labelBild.setText(_translate("BMIFenster", "<html><head/><body><p><img src=\"bmiRessourcen/Lama.png\"/></p></body></html>"))
        self.labelBMI.setText(_translate("BMIFenster", "BMI:"))
